### PR TITLE
Add GitHub workflows

### PR DESCRIPTION
**Pull request by stefanb2**

### CODE REVIEW

**Comment by stefanb2** [comment]
* tested with `act-cli` locally, except for the AppImage artifact upload.
* the workflows for Windows will be submitted as separate PR, because I can't test them locally on my Linux machine.

@bkueng I'll leave this PR in draft state as it relies on the cmake support being merged first.

**Comment by stefanb2** [comment]
OK, let's see if github actions are automatically enabled once this PR is merged...

**Comment by bkueng** [comment]
Strange, I would have expected them to run already

**Comment by stefanb2** [comment]
OK, AppImage generation fails on real GitHub, whereas it works fine with `act` locally....

**Pull request merged**
