### PR TITLE
Generate Windows installer package

### PR DESCRIPTION
**Pull request by stefanb2**
- switch to release builds
- switch to Windows 64-bit build
- install data files using CMake
- add custom target for `windeployqt`
- remove special case for translation handling on Windows
- add custom target for `makensis`

### CODE REVIEW

**Comment by stefanb2** [comment]
The Windows installer package installed & uninstalled fine on a Windows 10 VM.

**Review by bkueng — APPROVED** [review]
Nice!
Does the Windows installer also include the openssl lib?

**Comment by stefanb2** [comment]
> Does the Windows installer also include the openssl lib?

Of course `windeployqt` doesn't handle external libraries :-(

Strangely enough the installed program seems to run without the DLL, i.e. I tested it by running with empty `PATH`. Maybe there is some Windows mojo in the background that makes it find the installed DLL without `PATH`.

**Comment by stefanb2** [comment]
@bkueng I just checked the git history: the DLL also wasn't included in the original installer script.

So is this OK as it is or does it need more work?

**Comment by bkueng** [comment]
Alright let's get it in then. It was this one previously: https://github.com/bkueng/qMasterPassword/pull/44/files#diff-9fb3e1b8dae4229e02320dcc98f4d58f0a2c1ef104ca58b74c2d42a8dfb138c8L158. Looks like Qt already ships with it on Windows.

**Comment by stefanb2** [comment]
OK, I resolved the mystery. On the test VM I of course had to install an OpenSSL package for the build to succeed:

~~~
OpenSSL 3.1.4 (64-bit)                  ShiningLight.OpenSSL                       1.0.0
~~~

It seems that the package installs the DLL also in `C:\Windows\System32` and therefore it can be found also with empty `PATH`. Uninstalling the package doesn't remove the DLL from the system directory, so the program still works.

After manually deleting the DLLs from the system directory the installed program fails to start.

FYI: that package has been removed from `winget` repository in the last few days, so the only available OpenSSL package is now `FireDaemon.OpenSSL`, which doesn't install DLLs into the system directory and neither gets added to `PATH`. With that package installed the build goes through, but the resulting binary doesn't run, because the DLL can't be found from `PATH`.

So the user will need to install OpenSSL package by hand, otherwise the installed package won't work.

**Pull request merged**
