### PR TITLE
Remove dead files

### PR DESCRIPTION
**Pull request by stefanb2**
If they should still be needed it is easy to revive them from git history.

### CODE REVIEW

**Review by bkueng — APPROVED** [review]

**Comment by stefanb2** [comment]
(sorry for misusing the PR for this discussion, I can open an issue instead)

@bkueng I think it is time for the next release. IMHO this should not be a patch/minor release, i.e. 1.2.5 or 1.3.0, but 2.0.0 as there are breaking changes for package maintainers.

It would be cool if the release artifacts are automatically generated by CI, but I couldn't find any official GitHub action steps for this. So I guess you need to manually create the release page.

**Comment by bkueng** [comment]
Sure, do you have more upcoming changes to be included or should I trigger it right away?

**Comment by stefanb2** [comment]
No, no pending changes any more. Thanks!

**Comment by bkueng** [comment]
I created the release

**Comment by stefanb2** [comment]
> I created the release

Cool. Did GitHub automatically add the the assets from CI or did you add them by hand afterwards?

**Comment by bkueng** [comment]
I expected it to, but unfortunately it did not.
This action could be used for that: https://github.com/marketplace/actions/gh-release.

**Pull request merged**
