### PR TITLE
WIP: optimize windows build

### PR DESCRIPTION
**Pull request by stefanb2**
Instead of building scrypt-windows from scratch, use binary artifacts created by another repo.

### CODE REVIEW

**Comment by stefanb2** [comment]
@bkueng this would cut build time for the Windows workflows by about half.

**Comment by bkueng** [comment]
I was wondering if it's worth doing that, 5 min isn't terrible yet (I'm used to waiting much more on other projects).
But given it's that simple, we can certainly do that.
Another option would be to use ccache if there's a Windows-equivalent.

**Comment by stefanb2** [comment]
In my earlier life I got paid to be a SW Build Architect. Hence I hate slow, inefficient & unreliable SW builds.

Can you please create your own fork of barrysteyn/scrypt-windows and cherry-pick the GitHub action commit ontop of it? I only forked it, so I could create the commit, but I have no intention of maintaining the repo, as I don't have any Windows machines.

**Comment by stefanb2** [comment]
> Another option would be to use ccache if there's a Windows-equivalent.

Another option would be to add the few source code files from Tarsnap/scrypt under 3rdparty/ (in my understanding the real upstream source for scrypt code) to get the `crypto_scrypt()` function for Windows build. That would also mean that we have the latest version of it.

**Comment by bkueng** [comment]
> Another option would be to add the few source code files from Tarsnap/scrypt under 3rdparty/ (in my understanding the real upstream source for scrypt code) to get the crypto_scrypt() function for Windows build. That would also mean that we have the latest version of it.

That is my preferred approach, possibly as a submodule. But I haven't seen Windows as explicitly supported. It might be easy to get it to work. Do you want to look into that?

**Comment by stefanb2** [comment]
Sure, I'll take a stab at it.

**Comment by stefanb2** [comment]
Replaced by #43.

**Pull request closed without merging**
